"""
Behavior Analysis Engine — no LLM required.

Analyzes task completion/skip patterns from the database using
deterministic rules to produce the same output shape that was
previously generated by Gemini. Fully self-contained.
"""

from datetime import datetime
from typing import Optional

from .database import Database


# Human-readable labels for each time bucket
BUCKET_LABELS = {
    "morning":   "05:00–12:00",
    "afternoon": "12:00–17:00",
    "evening":   "17:00–21:00",
    "night":     "21:00–05:00",
}

# Thresholds
HIGH_COMPLETION  = 65.0   # success_rate >= this → productive
LOW_COMPLETION   = 45.0   # success_rate <  this → low-productivity
HIGH_SKIP        = 35.0   # skip% > this → avoidance pattern
MIN_SAMPLES      = 2      # need at least this many blocks to draw conclusions


# ── Public API ───────────────────────────────────────────────────────────────

def analyze_user_behavior(user_id: int, db: Optional[Database] = None) -> dict:
    """
    Analyse a user's behavioral patterns and return a dict matching the
    Gemini output shape so the rest of the system requires no changes.

    Return shape:
        {
          "analysis":   { productive_hours, low_productivity_hours,
                          preferred_task_types, avoided_task_types,
                          procrastination_patterns, consistency_score,
                          insights },
          "db_stats":   { consistency_score, total_blocks, completed_blocks,
                          skipped_blocks, skip_rate,
                          category_stats, time_bucket_stats },
          "generatedAt": "<ISO timestamp>"
        }
    """
    if db is None:
        db = Database()

    stats = db.get_behavior_stats(user_id)

    productive_hours  = _productive_hours(stats["time_buckets"])
    low_hours         = _low_productivity_hours(stats["time_buckets"])
    preferred         = _preferred_types(stats["categories"])
    avoided           = _avoided_types(stats["categories"])
    patterns          = _procrastination_patterns(stats)
    score             = _consistency_score(stats["block_totals"])
    insights          = _build_insights(stats, productive_hours, low_hours,
                                        preferred, avoided, score)

    return {
        "analysis": {
            "productive_hours":       productive_hours,
            "low_productivity_hours": low_hours,
            "preferred_task_types":   preferred,
            "avoided_task_types":     avoided,
            "procrastination_patterns": patterns,
            "consistency_score":      score,
            "insights":               insights,
        },
        "db_stats": {
            "consistency_score":  score,
            "total_blocks":       stats["block_totals"]["total"],
            "completed_blocks":   stats["block_totals"]["completed"],
            "skipped_blocks":     stats["block_totals"]["skipped"],
            "skip_rate":          stats["block_totals"]["skip_rate"],
            "category_stats":     stats["categories"],
            "time_bucket_stats":  stats["time_buckets"],
        },
        "generatedAt": datetime.utcnow().isoformat() + "Z",
    }


def get_behavior_hints(user_id: int, db: Optional[Database] = None) -> dict:
    """
    Lightweight summary used by the scheduler to bias task placement.
    Returns productive/low periods and per-category scores.
    """
    if db is None:
        db = Database()

    stats = db.get_behavior_stats(user_id)

    # Build period → success_rate map (default 50 if no data)
    period_scores = {b["period"]: b["success_rate"] for b in stats["time_buckets"]}
    for p in ("morning", "afternoon", "evening", "night"):
        period_scores.setdefault(p, 50.0)

    # Build category → success_rate map
    cat_scores = {c["category"]: c["success_rate"] for c in stats["categories"]}

    return {
        "period_scores": period_scores,
        "category_scores": cat_scores,
        "productive_periods":  _productive_hours(stats["time_buckets"]),
        "low_periods":         _low_productivity_hours(stats["time_buckets"]),
    }


# ── Internal helpers ─────────────────────────────────────────────────────────

def _consistency_score(totals: dict) -> int:
    if totals["total"] == 0:
        return 0
    return round((totals["completed"] / totals["total"]) * 100)


def _productive_hours(buckets: list) -> list:
    result = []
    for b in buckets:
        if b["total"] >= MIN_SAMPLES and b["success_rate"] >= HIGH_COMPLETION:
            result.append(BUCKET_LABELS[b["period"]])
    return result


def _low_productivity_hours(buckets: list) -> list:
    result = []
    for b in buckets:
        if b["total"] >= MIN_SAMPLES and b["success_rate"] < LOW_COMPLETION:
            result.append(BUCKET_LABELS[b["period"]])
    return result


def _preferred_types(categories: list) -> list:
    return [
        c["category"] for c in categories
        if c["total"] >= MIN_SAMPLES and c["success_rate"] >= HIGH_COMPLETION
    ]


def _avoided_types(categories: list) -> list:
    result = []
    for c in categories:
        if c["total"] < MIN_SAMPLES:
            continue
        skip_pct = (c["skipped"] / c["total"] * 100) if c["total"] > 0 else 0
        if c["success_rate"] < LOW_COMPLETION or skip_pct > HIGH_SKIP:
            result.append(c["category"])
    return result


def _procrastination_patterns(stats: dict) -> list:
    patterns = []
    totals = stats["block_totals"]

    # Overall skip rate
    if totals["skip_rate"] > 30:
        patterns.append(
            f"High skip rate of {totals['skip_rate']}% — tasks are frequently deferred rather than rescheduled"
        )

    # Evening/night avoidance
    for b in stats["time_buckets"]:
        if b["period"] in ("evening", "night") and b["total"] >= MIN_SAMPLES:
            skip_pct = round((b["skipped"] / b["total"]) * 100) if b["total"] > 0 else 0
            if skip_pct > 40:
                label = BUCKET_LABELS[b["period"]].split("–")[0]
                patterns.append(
                    f"{b['period'].title()} tasks are skipped {skip_pct}% of the time — "
                    f"avoid scheduling demanding work after {label}"
                )

    # Per-category avoidance
    for c in stats["categories"]:
        if c["total"] >= 3:
            skip_pct = round((c["skipped"] / c["total"]) * 100)
            if skip_pct > 40:
                patterns.append(
                    f"{c['category'].title()} tasks are skipped {skip_pct}% of the time — "
                    f"consider shorter, more focused sessions"
                )

    # Overloading: all buckets low
    well_covered = [b for b in stats["time_buckets"] if b["total"] >= MIN_SAMPLES]
    if well_covered and all(b["success_rate"] < 50 for b in well_covered):
        patterns.append(
            "Completion rates are low across all time slots — try scheduling 20% fewer tasks per day"
        )

    return patterns


def _build_insights(
    stats: dict,
    productive_hours: list,
    low_hours: list,
    preferred: list,
    avoided: list,
    score: int,
) -> list:
    insights = []
    totals = stats["block_totals"]

    # ── Consistency ──────────────────────────────────────────────────────────
    if totals["total"] == 0:
        insights.append("Not enough data yet — complete a few scheduled tasks to unlock insights")
        return insights

    if score >= 75:
        insights.append(
            f"Strong consistency at {score}% — your schedule is well-calibrated to your capacity"
        )
    elif score >= 50:
        insights.append(
            f"Moderate consistency at {score}% — small routine improvements could push this above 70%"
        )
    else:
        insights.append(
            f"Only {score}% of scheduled blocks are completed — "
            f"try scheduling 2–3 tasks per day instead of filling every slot"
        )

    # ── Best category ────────────────────────────────────────────────────────
    cats = sorted(stats["categories"], key=lambda c: c["success_rate"], reverse=True)
    if cats and cats[0]["total"] >= MIN_SAMPLES:
        best = cats[0]
        insights.append(
            f"{best['category'].title()} tasks have your highest completion rate at "
            f"{best['success_rate']:.0f}% — lean into this strength"
        )

    # ── Worst category ───────────────────────────────────────────────────────
    worst_candidates = [c for c in cats if c["total"] >= MIN_SAMPLES and c["success_rate"] < 60]
    if worst_candidates:
        worst = worst_candidates[-1]
        insights.append(
            f"{worst['category'].title()} tasks are your biggest challenge at "
            f"{worst['success_rate']:.0f}% — try 20-minute focused sessions instead of long blocks"
        )

    # ── Best time of day ─────────────────────────────────────────────────────
    t_sorted = sorted(
        [b for b in stats["time_buckets"] if b["total"] >= MIN_SAMPLES],
        key=lambda b: b["success_rate"],
        reverse=True,
    )
    if t_sorted:
        best_t = t_sorted[0]
        insights.append(
            f"Your {best_t['period']} ({BUCKET_LABELS[best_t['period']]}) is most productive "
            f"at {best_t['success_rate']:.0f}% — schedule your hardest tasks here"
        )

    # ── Skip rate warning ────────────────────────────────────────────────────
    if totals["skip_rate"] > 25:
        insights.append(
            f"{totals['skip_rate']}% skip rate signals overcommitment — "
            f"identify your top 3 daily priorities and protect them from context switches"
        )

    # ── Low-productivity time advice ─────────────────────────────────────────
    if low_hours:
        insights.append(
            f"Your {', '.join(low_hours)} hours have the lowest completion rates — "
            f"reserve these for admin, reviews, or planned breaks"
        )

    # ── Avoided categories advice ────────────────────────────────────────────
    if avoided:
        insights.append(
            f"You frequently skip {', '.join(avoided)} tasks — "
            f"try pairing them with a preferred category or moving them to your productive window"
        )

    return insights
