import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:shared_preferences/shared_preferences.dart';
import '../theme/app_theme.dart';
import 'login_screen.dart';

class OnboardingScreen extends StatefulWidget {
  const OnboardingScreen({super.key});

  static Future<bool> shouldShow() async {
    final prefs = await SharedPreferences.getInstance();
    return prefs.getBool('onboarding_done') != true;
  }

  static Future<void> markDone() async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.setBool('onboarding_done', true);
  }

  @override
  State<OnboardingScreen> createState() => _OnboardingScreenState();
}

class _OnboardingScreenState extends State<OnboardingScreen>
    with TickerProviderStateMixin {
  final _pageCtrl = PageController();
  int _page = 0;

  late final List<AnimationController> _animCtrls;
  late final List<Animation<double>> _fadeAnims;
  late final List<Animation<Offset>> _slideAnims;

  final _steps = const [
    _Step(
      icon: Icons.auto_awesome_rounded,
      iconColor: AppColors.accent,
      title: 'AI-powered planning',
      body:
          'Your schedule is generated by AI — it learns your habits and builds a plan that actually fits your life.',
    ),
    _Step(
      icon: Icons.add_task_rounded,
      iconColor: AppColors.catHealth,
      title: 'Add your first task',
      body:
          'Tell the app what you need to do, when, and how long. Set it once — the AI handles the rest.',
    ),
    _Step(
      icon: Icons.insights_rounded,
      iconColor: AppColors.cyan,
      title: 'Track your progress',
      body:
          'Complete blocks as you go, build streaks, and get AI insights on your productivity patterns.',
    ),
  ];

  @override
  void initState() {
    super.initState();
    _animCtrls = List.generate(
      _steps.length,
      (i) => AnimationController(
          vsync: this, duration: const Duration(milliseconds: 500)),
    );
    _fadeAnims = _animCtrls
        .map((c) => CurvedAnimation(parent: c, curve: Curves.easeOut))
        .toList();
    _slideAnims = _animCtrls
        .map((c) => Tween<Offset>(
                begin: const Offset(0, 0.08), end: Offset.zero)
            .animate(CurvedAnimation(parent: c, curve: Curves.easeOutCubic)))
        .toList();
    _animCtrls[0].forward();
  }

  @override
  void dispose() {
    _pageCtrl.dispose();
    for (final c in _animCtrls) {
      c.dispose();
    }
    super.dispose();
  }

  void _next() {
    if (_page < _steps.length - 1) {
      _pageCtrl.nextPage(
          duration: const Duration(milliseconds: 350), curve: Curves.easeInOut);
    } else {
      _finish();
    }
  }

  void _finish() async {
    await OnboardingScreen.markDone();
    if (!mounted) return;
    Navigator.pushReplacement(
        context, MaterialPageRoute(builder: (_) => const LoginScreen()));
  }

  @override
  Widget build(BuildContext context) {
    final isDark = Theme.of(context).brightness == Brightness.dark;

    return Scaffold(
      backgroundColor: isDark ? AppColors.darkBg : AppColors.lightBg,
      body: Stack(children: [
        // Ambient glow
        Positioned(
          top: -80, left: -60,
          child: _Blob(color: AppColors.accent, size: 320,
              opacity: isDark ? 0.14 : 0.08),
        ),
        Positioned(
          bottom: -60, right: -40,
          child: _Blob(color: AppColors.cyan, size: 260,
              opacity: isDark ? 0.10 : 0.06),
        ),
        Column(children: [
          // Skip
          SafeArea(
            child: Align(
              alignment: Alignment.centerRight,
              child: Padding(
                padding: const EdgeInsets.fromLTRB(0, 8, 16, 0),
                child: TextButton(
                  onPressed: _finish,
                  child: Text('Skip',
                      style: GoogleFonts.inter(
                          color: isDark ? AppColors.darkMuted : AppColors.lightMuted,
                          fontWeight: FontWeight.w500,
                          fontSize: 14)),
                ),
              ),
            ),
          ),
          // Pages
          Expanded(
            child: PageView.builder(
              controller: _pageCtrl,
              itemCount: _steps.length,
              onPageChanged: (i) {
                setState(() => _page = i);
                _animCtrls[i].forward(from: 0);
              },
              itemBuilder: (_, i) => FadeTransition(
                opacity: _fadeAnims[i],
                child: SlideTransition(
                  position: _slideAnims[i],
                  child: Padding(
                    padding: const EdgeInsets.symmetric(horizontal: 32),
                    child: Column(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        Container(
                          width: 96, height: 96,
                          decoration: BoxDecoration(
                            shape: BoxShape.circle,
                            color: _steps[i].iconColor.withValues(alpha: 0.12),
                            border: Border.all(
                                color: _steps[i].iconColor.withValues(alpha: 0.25)),
                          ),
                          child: Icon(_steps[i].icon,
                              color: _steps[i].iconColor, size: 44),
                        ),
                        const SizedBox(height: 40),
                        Text(
                          _steps[i].title,
                          style: GoogleFonts.inter(
                            fontSize: 26,
                            fontWeight: FontWeight.w700,
                            color: isDark ? AppColors.darkText : AppColors.lightText,
                            height: 1.2,
                          ),
                          textAlign: TextAlign.center,
                        ),
                        const SizedBox(height: 16),
                        Text(
                          _steps[i].body,
                          style: GoogleFonts.inter(
                            fontSize: 15,
                            color: isDark ? AppColors.darkMuted : AppColors.lightMuted,
                            height: 1.6,
                          ),
                          textAlign: TextAlign.center,
                        ),
                      ],
                    ),
                  ),
                ),
              ),
            ),
          ),
          // Dots + button
          Padding(
            padding: const EdgeInsets.fromLTRB(32, 0, 32, 48),
            child: Column(children: [
              // Dots
              Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: List.generate(_steps.length, (i) {
                  final active = i == _page;
                  return AnimatedContainer(
                    duration: const Duration(milliseconds: 250),
                    margin: const EdgeInsets.symmetric(horizontal: 4),
                    width: active ? 24 : 6,
                    height: 6,
                    decoration: BoxDecoration(
                      color: active
                          ? AppColors.accent
                          : (isDark ? AppColors.darkBorder2 : AppColors.lightBorder),
                      borderRadius: BorderRadius.circular(3),
                    ),
                  );
                }),
              ),
              const SizedBox(height: 32),
              // CTA button
              _OnboardingButton(
                label: _page == _steps.length - 1 ? 'Get started' : 'Next',
                onTap: _next,
              ),
            ]),
          ),
        ]),
      ]),
    );
  }
}

class _Step {
  final IconData icon;
  final Color iconColor;
  final String title;
  final String body;
  const _Step(
      {required this.icon,
      required this.iconColor,
      required this.title,
      required this.body});
}

class _Blob extends StatelessWidget {
  final Color color;
  final double size;
  final double opacity;
  const _Blob({required this.color, required this.size, required this.opacity});

  @override
  Widget build(BuildContext context) => Container(
    width: size, height: size,
    decoration: BoxDecoration(
      shape: BoxShape.circle,
      gradient: RadialGradient(
          colors: [color.withValues(alpha: opacity), Colors.transparent]),
    ),
  );
}

class _OnboardingButton extends StatefulWidget {
  final String label;
  final VoidCallback onTap;
  const _OnboardingButton({required this.label, required this.onTap});

  @override
  State<_OnboardingButton> createState() => _OnboardingButtonState();
}

class _OnboardingButtonState extends State<_OnboardingButton> {
  bool _hovered = false;

  @override
  Widget build(BuildContext context) => MouseRegion(
    onEnter: (_) => setState(() => _hovered = true),
    onExit: (_) => setState(() => _hovered = false),
    child: AnimatedContainer(
      duration: const Duration(milliseconds: 200),
      height: 52,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(14),
        gradient: const LinearGradient(
            colors: [AppColors.accent, Color(0xFF5B21B6)]),
        boxShadow: [
          BoxShadow(
            color: AppColors.accent.withValues(alpha: _hovered ? 0.50 : 0.30),
            blurRadius: _hovered ? 20 : 12,
            offset: const Offset(0, 4),
          ),
        ],
      ),
      child: Material(
        color: Colors.transparent,
        child: InkWell(
          borderRadius: BorderRadius.circular(14),
          onTap: widget.onTap,
          child: Center(
            child: Text(widget.label,
                style: GoogleFonts.inter(
                    color: Colors.white,
                    fontWeight: FontWeight.w600,
                    fontSize: 15)),
          ),
        ),
      ),
    ),
  );
}
